version: '3'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres
    restart: always
    hostname: postgres
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/postgresql:/var/lib/postgresql/data
  web:
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /etc/shadow:/etc/shadow
      - /var/sites/${COMPOSE_PROJECT_NAME}/django:/app
    image: sgsullivan/python3-django-postgres-celery-rabbitmq:latest
    restart: always
    command: /lw/bootstrap
    hostname: django
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEB_PORT=${WEB_PORT}
      - RMQ_CLUSTER=${RMQ_CLUSTER}
      - RMQ_USER=${RMQ_USER}
      - RMQ_PASSWORD=${RMQ_PASSWORD}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - postgres
  rabbitmq:
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
  celery:
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /etc/shadow:/etc/shadow
      - /var/sites/${COMPOSE_PROJECT_NAME}/django:/app
    image: sgsullivan/python3-django-postgres-celery-rabbitmq:latest
    restart: always
    command: /lw/bootstrap-celery
    hostname: celery
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RMQ_CLUSTER=${RMQ_CLUSTER}
      - RMQ_USER=${RMQ_USER}
      - RMQ_PASSWORD=${RMQ_PASSWORD}
    depends_on:
      - rabbitmq
      - web
  ssh:
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /etc/shadow:/etc/shadow
      - /var/sites/${COMPOSE_PROJECT_NAME}/django:/home/${COMPOSE_PROJECT_NAME}
    ports:
      - ${SSH_PORT}:22
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RMQ_CLUSTER=${RMQ_CLUSTER}
      - RMQ_USER=${RMQ_USER}
      - RMQ_PASSWORD=${RMQ_PASSWORD}
    image: sgsullivan/python3-django-postgres-celery-rabbitmq-ssh:latest
    hostname: ${COMPOSE_PROJECT_NAME}
    restart: always
