version: '3'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres
    restart: always
    hostname: postgres
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/postgresql:/var/lib/postgresql/data
  web:
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/django:/app
    image: sgsullivan/python3-django-postgres:latest
    restart: always
    hostname: django
    command: /lw/bootstrap
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEB_PORT=${WEB_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - postgres
  ssh:
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /etc/shadow:/etc/shadow
      - /var/sites/${COMPOSE_PROJECT_NAME}/django:/home/${COMPOSE_PROJECT_NAME}
    ports:
      - ${SSH_PORT}:22
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RMQ_CLUSTER=${RMQ_CLUSTER}
      - RMQ_USER=${RMQ_USER}
      - RMQ_PASSWORD=${RMQ_PASSWORD}
    image: sgsullivan/python3-django-postgres-ssh:latest
    hostname: ${COMPOSE_PROJECT_NAME}
    restart: always

