version: '3'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres
    restart: always
    hostname: postgres
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/postgresql:/var/lib/postgresql/data
  web:
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/django:/app
    image: sgsullivan/python3-django-postgres-celery-rabbitmq:latest
    restart: always
    hostname: django
    command: /lw/bootstrap
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEB_PORT=${WEB_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - postgres
