version: '3'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres
    restart: always
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/postgresql:/var/lib/postgresql/data
  web:
    volumes:
      - /var/sites/${COMPOSE_PROJECT_NAME}/django:/app
    image: sgsullivan/python3-django:latest
    restart: always
    command: /lw/bootstrap
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEB_PORT=${WEB_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - db
